---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Run command on all targets
    command: "{{ input_command }}"
    register: command_output_full

  - name: Print commands
    debug: 
      var: command_output_full.stdout